### ISSUE TITLE
No such file or class on classpath: runtime.Main

### ISSUE THREAD

**Issue by calvertdw** [brendon-boldt/improved-halstead#1]
This project doesn't run for me. I get:
```
$ scala -cp $CLASSPATH:cgrammar.jar runtime.Main SomeFile.java 
No such file or class on classpath: runtime.Main
```

**Comment by calvertdw** [comment]
I found that you need to call `make` first. Could that be added to the README?

Also, this project depends on antlr4 and antlr4-runtime, which need to be downloaded and put on the classpath manually.

Also, in newer Scala, MutableList is gone, must use ArrayDeque instead.

I am still stuck on the error now:
```
java.lang.ClassNotFoundException: org.antlr.v4.runtime.CharStream
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at runtime.Main$.main(main.scala:10)
        at runtime.Main.main(main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```
